baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hícaro"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hícaro"
  description: My personal website
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hícaro" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Hícaro Dânrlley."
    content: "A passionate software developer."
    image: /images/me1.jpeg
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/drive/folders/1HEgd8xXOdbcE1ve6Uhzkxa3vlJ06AfjY?usp=share_link"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/HicaroD

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me2.jpeg"
    content: |-
      I'm a Computer Science student and a software developer. I started my journey in coding two 
      years ago with C programming language. Ever since, I've been writing software in multiple 
      programming languages, such as Python, JavaScript, Typescript, Dart, Go, Rust  and more.

      At first, I wanted to be a lawyer, but a great friend of mine told me about a Harvard course 
      called CS50 and that changed my life forever (Thanks, Alice). I also want to appreciate my best
      friends: Pedro, Isadora and my cousin Alícia, life is so much better with you all. 
      And most importantly, I love you, mom, I will dedicate my entire life just to make you proud of
      me.
        
      By day I'm a Flutter developer building mobile apps. 
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "Dart"
        - "Flutter"
        - "Typescript"
        - "NodeJS"
        - "ExpressJS"
        - "MongoDB"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Mobile developer"
        company: "Otimize"
        companyUrl: "https://otimize.tec.br/index/"
        date: "Aug 2021 - present"
        content: "I am currently working as a mobile developer developer at [Otimize](https://otimize.tec.br/index/) in Arapiraca, Brazil."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Universidade Federal de Alagoas - UFAL"
          url: "https://ufal.br/"
        date: "2021 - present"

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Pomo
        content: |- 
          "Pomo" is a mobile app that implements the Pomodoro technique to make you more productive.
          This project is a work in progress, but, in the future, you will be able to analyze your
          productivity.
        image: /images/projects/pomo.jpeg
        badges:
          - "Flutter"
        links:
          - icon: fab fa-github
            url: https://github.com/PomoOrg/Pomo

      - title: RESTful API for Pomo
        content: |- 
          This API was built with NodeJS. In the back-end, I'm using ExpressJS to build a RESTful API.
          To store all the data, I'm using MongoDB as NoSQL database. For security, I'm encrypting
          sensitive informations, such as passwords, using bcrypt and JSON Web Token (JWT)
          for user authentication.
        image: /images/projects/pomo.jpeg
        badges:
          - "NodeJS"
          - "Express"
          - "MongoDB"
          - "bcrypt"
          - "JWT"
        links:
          - icon: fab fa-github
            url: https://github.com/PomoOrg/Pomo-API

      - title: TodoAsIssue
        content: |- 
          TodoAsIssue is a command-line interface that helps to create issues on your repository
          hosted on GitHub or GitLab.
        image: /images/projects/todo_as_issue_project.png
        badges:
          - "Dart"
          - "RESTful API"
          - "CLI"
        links:
          - icon: fab fa-github
            url: https://github.com/HicaroD/TodoAsIssue

      - title: PullRequests
        content: |- 
          PullRequest is a command-line interface that helps to create pull requests on your repository
          hosted on GitHub.
        image: /images/projects/pull_request_project.jpg
        badges:
          - "Python"
          - "RESTful API"
          - "CLI"
        links:
          - icon: fab fa-github
            url: https://github.com/HicaroD/pull-requests

      - title: Portfolio website
        content: |- 
          That's just my old portfolio website built with Django.
        image: /images/projects/old_portfolio_website_project.png
        badges:
          - "Python"
          - "Django"
          - "HTML"
          - "CSS"
          - "JavaScript"
          - "Heroku"
        links:
          - icon: fab fa-github
            url: https://github.com/HicaroD/portfolio-website

      - title: Conway's Game of Life
        content: |- 
          My own implementation of Conway's Game of Life written in C++ and SDL2.
        image: /images/projects/game_of_life_project.jpg
        badges:
          - "C++"
          - "SDL2"
        featured:
          name: Demo
          link: https://youtu.be/3e47CYvVRYQ
        links:
          - icon: fab fa-github
            url: https://github.com/HicaroD/game-of-life
              

  #Contact
  contact:
    enable: true
    title: "Contact"
    content: My inbox is always open for business inquiries.
    email: hdanrlley1@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: true
    socialNetworks:
      github: https://github.com/HicaroD
      linkedin: https://linkedin.com/in/hicaromiguel

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

